"""
Django settings for knowledge_manager project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# ===== GPU Auto-Detection =====
def _detect_device():
    """Auto-detect best available compute device (CUDA > CPU). Gracefully falls back if torch is missing."""
    try:
        import torch
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
            print(f"[GPU] Detected: {gpu_name} | VRAM: {vram_gb:.1f} GB | Using CUDA")
            return 'cuda'
        print("[GPU] No CUDA device found — running on CPU")
        return 'cpu'
    except ImportError:
        print("[GPU] torch not installed — defaulting to CPU")
        return 'cpu'

AUTO_DEVICE = _detect_device()
USE_GPU = AUTO_DEVICE == 'cuda'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i4-vl+&zf2$2ofug05u%qe8j73d%2num=pomwb%zknr4r!s!x&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'app_core',
    'coding_ide',
    'django_apscheduler',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "knowledge_manager.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'coding_ide.context_processors.gpu_context',
            ],
        },
    },
]

WSGI_APPLICATION = "knowledge_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ===== RAG & AI Configuration =====

# Ollama Configuration
OLLAMA_HOST = config('OLLAMA_HOST', default='http://localhost:11434')
OLLAMA_MODEL = config('OLLAMA_MODEL', default='llama3.2:1b')
OLLAMA_TIMEOUT = config('OLLAMA_TIMEOUT', default=120, cast=int)

# Embedding Configuration
EMBEDDING_MODEL = config('EMBEDDING_MODEL', default='intfloat/multilingual-e5-small')
# EMBEDDING_MODEL = config('EMBEDDING_MODEL', default='sentence-transformers/all-MiniLM-L6-v2')
MODELS_CACHE_DIR = BASE_DIR / config('MODELS_CACHE_DIR', default='models_cache')
EMBEDDING_BATCH_SIZE = config('EMBEDDING_BATCH_SIZE', default=16, cast=int)
EMBEDDING_DEVICE = config('EMBEDDING_DEVICE', default=AUTO_DEVICE)

# FAISS Configuration
FAISS_INDEX_PATH = BASE_DIR / config('FAISS_INDEX_PATH', default='faiss_index')
FAISS_TOP_K = config('FAISS_TOP_K', default=3, cast=int)
CHUNK_SIZE = config('CHUNK_SIZE', default=200, cast=int)
CHUNK_OVERLAP = config('CHUNK_OVERLAP', default=50, cast=int)

# Memory Optimization
MAX_CONCURRENT_EMBEDDINGS = config('MAX_CONCURRENT_EMBEDDINGS', default=1, cast=int)
ENABLE_QUERY_CACHE = config('ENABLE_QUERY_CACHE', default=True, cast=bool)
QUERY_CACHE_SIZE = config('QUERY_CACHE_SIZE', default=50, cast=int)

# Upload Settings
MAX_UPLOAD_SIZE = config('MAX_UPLOAD_SIZE', default=50, cast=int) * 1024 * 1024  # Convert MB to bytes
ALLOWED_EXTENSIONS = config('ALLOWED_EXTENSIONS', default='.pdf,.docx,.txt,.xlsx', cast=Csv())

# Create necessary directories
os.makedirs(MODELS_CACHE_DIR, exist_ok=True)
os.makedirs(FAISS_INDEX_PATH, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)

# ===== Coding IDE Configuration =====

# Ollama model for code generation (Qwen 2.5 Coder — optimized for 8 GB VRAM)
CODING_OLLAMA_HOST = config('CODING_OLLAMA_HOST', default='http://localhost:11434')
CODING_OLLAMA_MODEL = config('CODING_OLLAMA_MODEL', default='qwen2.5-coder:7b')
CODING_OLLAMA_TIMEOUT = config('CODING_OLLAMA_TIMEOUT', default=180, cast=int)

# Code embedding model (code-aware)
CODE_EMBEDDING_MODEL = config('CODE_EMBEDDING_MODEL', default='sentence-transformers/all-MiniLM-L6-v2')
CODE_MODELS_CACHE_DIR = BASE_DIR / config('CODE_MODELS_CACHE_DIR', default='code_models_cache')
CODE_EMBEDDING_BATCH_SIZE = config('CODE_EMBEDDING_BATCH_SIZE', default=8, cast=int)
CODE_EMBEDDING_DEVICE = config('CODE_EMBEDDING_DEVICE', default=AUTO_DEVICE)

# Code FAISS index (separate from docs)
CODE_FAISS_INDEX_PATH = BASE_DIR / config('CODE_FAISS_INDEX_PATH', default='code_faiss_index')
CODE_FAISS_TOP_K = config('CODE_FAISS_TOP_K', default=5, cast=int)

# Code chunking (larger chunks to preserve context)
CODE_CHUNK_SIZE = config('CODE_CHUNK_SIZE', default=400, cast=int)
CODE_CHUNK_OVERLAP = config('CODE_CHUNK_OVERLAP', default=80, cast=int)

# Supported code file extensions
CODE_ALLOWED_EXTENSIONS = config(
    'CODE_ALLOWED_EXTENSIONS',
    default='.py,.js,.ts,.java,.cpp,.c,.h,.go,.rs,.php,.rb,.swift,.kt,.cs,.html,.css,.sql,.sh,.md,.json,.yaml,.yml,.toml,.txt',
    cast=Csv()
)

# Query cache
CODE_ENABLE_QUERY_CACHE = config('CODE_ENABLE_QUERY_CACHE', default=True, cast=bool)
CODE_QUERY_CACHE_SIZE = config('CODE_QUERY_CACHE_SIZE', default=30, cast=int)

# Create necessary directories
os.makedirs(CODE_MODELS_CACHE_DIR, exist_ok=True)
os.makedirs(CODE_FAISS_INDEX_PATH, exist_ok=True)

# ===== GPU / FAISS Settings =====
# When USE_GPU=True the FAISS managers will move indexes to GPU memory for faster search.
# Requires: pip install faiss-gpu-cu12  (CUDA 12.x)  or  faiss-gpu  (CUDA 11.x)
FAISS_USE_GPU = config('FAISS_USE_GPU', default=USE_GPU, cast=bool)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'knowledge_manager.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'app_core': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'coding_ide': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}